# Generated by Django 3.2.9 on 2021-11-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(verbose_name=models.DateTimeField(auto_now_add=True)),
        ),
    ]
