# Generated by Django 3.2.9 on 2021-11-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chat', '0002_auto_20211123_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
