# Generated by Django 3.2.9 on 2021-11-25 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chat', '0004_alter_chat_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 3, 8, 7, 352253)),
        ),
    ]
