# Generated by Django 3.2.9 on 2021-11-25 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chat', '0005_auto_20211125_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room',
            field=models.CharField(default='dev_room', max_length=255),
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 14, 54, 6, 113118)),
        ),
    ]
