# Generated by Django 3.2.9 on 2021-11-25 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chat', '0006_auto_20211125_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 17, 32, 57, 43790)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=1500),
        ),
    ]
