# Generated by Django 3.2.9 on 2021-11-25 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chat', '0007_auto_20211125_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 21, 29, 23, 532784)),
        ),
    ]
